Create Database Kereta_Api;

CREATE TABLE PEMESAN(
ID_PEMESAN VARCHAR(5),
NAMA_PEMESAN VARCHAR(100),
ALAMAT VARCHAR(100),
TLP VARCHAR(20),
CONSTRAINT PK_PEMESAN_ID_PEMESAN PRIMARY KEY (ID_PEMESAN)
);


CREATE TABLE PENUMPANG(
NO_IDENTITAS VARCHAR(30),
NAMA_PENUMPANG VARCHAR(100),
GOLONGAN VARCHAR(20),
ID_PEMESAN VARCHAR(5),
CONSTRAINT PK_PENUMPANG_NO_IDENTITAS PRIMARY KEY(NO_IDENTITAS),
CONSTRAINT FK_PENUMPANG_ID_PEMESAN FOREIGN KEY (ID_PEMESAN) REFERENCES PEMESAN(ID_PEMESAN)
);


CREATE TABLE KOTA (
ID_KOTA VARCHAR(5),
NAMA_KOTA VARCHAR(50),
CONSTRAINT PK_KOTA_ID_KOTA PRIMARY KEY (ID_KOTA)
);

CREATE TABLE STASIUN (
ID_STASIUN VARCHAR(5),
NAMA_STASIUN VARCHAR(50),
ID_KOTA VARCHAR(5),
CONSTRAINT PK_STASIUN_ID_STASIUN PRIMARY KEY (ID_STASIUN),
CONSTRAINT FK_STASIUN_ID_KOTA FOREIGN KEY (ID_KOTA) REFERENCES KOTA(ID_KOTA)
);

CREATE TABLE TUJUAN(
ID_TUJUAN VARCHAR(5),
ID_STASIUN VARCHAR(5),
CONSTRAINT PK_TUJUAN_ID_TUJUAN PRIMARY KEY (ID_TUJUAN),
CONSTRAINT FK_TUJUAN_ID_STASIUN FOREIGN KEY (ID_STASIUN) REFERENCES STASIUN(ID_STASIUN)
);

CREATE TABLE ASAL(
ID_ASAL VARCHAR(5),
ID_STASIUN VARCHAR(5),
CONSTRAINT PK_ASAL_ID_ASAL PRIMARY KEY (ID_ASAL),
CONSTRAINT FK_ASAL_ID_STASIUN FOREIGN KEY (ID_STASIUN) REFERENCES STASIUN(ID_STASIUN)
);

CREATE TABLE JURUSAN(
ID_JURUSAN VARCHAR(5),
ID_ASAL VARCHAR(5),
ID_TUJUAN VARCHAR(5),
CONSTRAINT PK_JURUSAN_ID_JURUSAN PRIMARY KEY (ID_JURUSAN),
CONSTRAINT FK_JURUSAN_ID_ASAL FOREIGN KEY (ID_ASAL) REFERENCES ASAL(ID_ASAL),
CONSTRAINT FK_JURUSAN_ID_TUJUAN FOREIGN KEY (ID_TUJUAN) REFERENCES TUJUAN(ID_TUJUAN)
);


CREATE TABLE KERETA(
NO_KERETA VARCHAR(5),
NAMA_KERETA VARCHAR(50),
KELAS VARCHAR(20),
TARIF_KERETA NUMERIC(8,0),
ID_JURUSAN VARCHAR(5),
CONSTRAINT PK_KERETA_NO_KERETA PRIMARY KEY (NO_KERETA),
CONSTRAINT FK_KERETA_ID_JURUSAN FOREIGN KEY (ID_JURUSAN) REFERENCES JURUSAN(ID_JURUSAN)
);

CREATE TABLE JADWAL(
NO_KERETA VARCHAR(5),
ID_STASIUN VARCHAR(5),
JAM_DTG DATETIME,
JAM_BGKT DATETIME,
CONSTRAINT FK_JADWAL_NO_KERETA FOREIGN KEY (NO_KERETA) REFERENCES KERETA(NO_KERETA),
CONSTRAINT FK_JADWAL_ID_STASIUN FOREIGN KEY  (ID_STASIUN) REFERENCES STASIUN(ID_STASIUN)
);

CREATE TABLE GERBONG(
ID_GERBONG VARCHAR(5),
NO_KERETA VARCHAR(5),
JUMLAH_KURSI INT,
CONSTRAINT PK_GERBONG_ID_GERBONG PRIMARY KEY (ID_GERBONG),
CONSTRAINT FK_GERBONG_NO_KERETA FOREIGN KEY (NO_KERETA) REFERENCES KERETA(NO_KERETA)
);


CREATE;I VARCHAR(20),
CONSTRAINT PK_KURSI_ID_KURSI PRIMARY KEY (ID_KURSI),
CONSTRAINT FK_KURSI_ID_GERBONG FOREIGN KEY (ID_GERBONG)REFERENCES GERBONG(ID_GERBONG)
);


CREATE TABLE BUKTI_PEMESANAN(
NO_BOOKING VARCHAR(5),
TGL_PESAN DATETIME,
TGL_BGKT DATETIME,
STATUS_PESAN VARCHAR(20),
NO_IDENTITAS VARCHAR(30),
ID_GERBONG VARCHAR(5),
CONSTRAINT PK_BUKTI_PEMESANAN_NO_BOOKING PRIMARY KEY (NO_BOOKING),
CONSTRAINT FK_BUKTI_PEMESANAN_NO_IDENTITAS FOREIGN KEY (NO_IDENTITAS) REFERENCES PENUMPANG(NO_IDENTITAS),
CONSTRAINT FK_BUKTI_PEMESANAN_ID_GERBONG FOREIGN KEY (ID_GERBONG) REFERENCES GERBONG (ID_GERBONG)
);


CREATE TABLE DETIL_PEMESANAN(
NO_BOOKING VARCHAR(5),
ID_KURSI VARCHAR(5),
TARIF NUMERIC(8,0),
CONSTRAINT FK_DETIL_PEMESANAN_NO_BOOKING FOREIGN KEY (NO_BOOKING) REFERENCES BUKTI_PEMESANAN(NO_BOOKING),
CONSTRAINT FK_DETIL_PEMESANAN_ID_KURSI FOREIGN KEY (ID_KURSI) REFERENCES KURSI(ID_KURSI)
);



-- INSERT DATA


-- TABEL KERETA
