-- Insert Table KOTA
SP_HELP KOTA

INSERT INTO KOTA VALUES ('BDG','Bandung');
INSERT INTO KOTA VALUES ('BJR','Banjar');
INSERT INTO KOTA VALUES ('BMS','Banyumas');
INSERT INTO KOTA VALUES ('BWI','Banyuwangi');
INSERT INTO KOTA VALUES ('BTG','Batang');
INSERT INTO KOTA VALUES ('BTA','Baturaja');
INSERT INTO KOTA VALUES ('BKS','Bekasi');
INSERT INTO KOTA VALUES ('BJI','Binjai');
INSERT INTO KOTA VALUES ('JKT','Jakarta');
INSERT INTO KOTA VALUES ('SBY','Surabaya');


-- Insert Table Stasiun Jakarta

INSERT INTO STASIUN VALUES ('GMR','Gambir','JKT');
INSERT INTO STASIUN VALUES ('JAKK','Jakarta Kota','JKT');
INSERT INTO STASIUN VALUES ('JNG','Jatinegara','JKT');

-- Insert Table Stasiun Surabaya
INSERT INTO STASIUN VALUES ('SGU','Surabaya Gubeng','SBY');
INSERT INTO STASIUN VALUES ('SBI','Surabaya Pasar Turi','SBY');
INSERT INTO STASIUN VALUES ('WO','Wonokromo','SBY');



